export enum CSV_TEMPLATES_NAMES {
  COURSE = "COURSE",
  GOAL = "GOAL",
  WORKER_COURSE = "WORKER_COURSE",
  INDICATOR_COURSE = "INDICATOR_COURSE",
  INDICATOR = "INDICATOR",
  COMPANY = "COMPANY",
  PRODUCER = "PRODUCER",
  INDICATOR_VALUE = "INDICATOR_VALUE",
}

export const templatesList: CSV_TEMPLATES_NAMES[] = [
  CSV_TEMPLATES_NAMES.COMPANY,
  CSV_TEMPLATES_NAMES.COURSE,
  CSV_TEMPLATES_NAMES.GOAL,
  CSV_TEMPLATES_NAMES.INDICATOR,
  CSV_TEMPLATES_NAMES.INDICATOR_COURSE,
  CSV_TEMPLATES_NAMES.INDICATOR_VALUE,
  CSV_TEMPLATES_NAMES.PRODUCER,
  CSV_TEMPLATES_NAMES.WORKER_COURSE,
];
